dataset:
    name: &dataset_name 'imagenet'
    root: &data_dir './resource/data/ILSVRC2012/'
    data:
        train: !join [*data_dir, 'train.txt']
        valid: !join [*data_dir, 'valid.txt']
        test: !join [*data_dir, 'valid.txt']
    normalizer:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

input_shape: [3, 299, 299]

model:
    type: &model_type 'inception_v3'
    experiment: &experiment !join [*dataset_name, '-', *model_type]
    pretrained: True
    ckpt: !join ['./resource/ckpt/org/', *experiment, '.ckpt']
    params:
        num_classes: 1000
        aux_logits: False
        transform_input: False

train:
    epoch: 50
    batch_size: 20
    rough_size: 299
    interval: 50
    optimizer:
        type: 'sgd'
        params:
            lr: 0.01
            momentum: 0.9
            weight_decay: 0.0005
    criterion:
        type: 'CrossEntropyLoss'
        params:
            reduction: 'elementwise_mean'

test:
    batch_size: 1
    jquality: 0
    compression:
        type:
        size:
    autoencoder:
