dataset:
    name: &dataset_name 'caltech101'
    root: &data_dir './resource/data/caltech101/'
    data:
        train: !join [*data_dir, 'train.txt']
        valid: !join [*data_dir, 'valid.txt']
        test: !join [*data_dir, 'test.txt']
    normalizer:
        mean:
        std:

input_shape: [3, 224, 224]

model:
    type: &model_type 'densenet169'
    experiment: &experiment !join [*dataset_name, '-', *model_type]
    pretrained: False
    ckpt: !join ['./resource/ckpt/', *experiment, '.ckpt']
    params:
        growth_rate: 32
        block_config: [6, 12, 32, 32]
        num_init_features: 64
        bn_size: 4
        drop_rate: 0
        num_classes: 101
        # Default parameters for input size(3, 224, 224)
        conv2d_ksize: 7
        conv2d_stride: 2
        conv2d_padding: 3
        maxpool_2d_ksize: 3
        maxpool_2d_stride: 2
        maxpool_2d_padding: 1
        avg_pool2d_ksize: 7

train:
    epoch: 200
    batch_size: 20
    rough_size: [256, 256]
    interval: -1
    optimizer:
        type: 'SGD'
        params:
            lr: 0.1
            momentum: 0.9
            weight_decay: 0.0005
    scheduler:
        type: 'MultiStepLR'
        params:
            milestones: [50, 100, 150, 200]
            gamma: 0.1
    criterion:
        type: 'CrossEntropyLoss'
        params:
            reduction: 'elementwise_mean'

test:
    batch_size: 1
    jquality: 0
    compression:
        type:
        size:
