dataset:
    name: &dataset_name 'caltech101'
    root: &data_dir './resource/data/caltech101/'
    data:
        train: !join [*data_dir, 'train.txt']
        valid: !join [*data_dir, 'valid.txt']
        test: !join [*data_dir, 'test.txt']
    normalizer:
        mean:
        std:

input_shape: [3, 224, 224]

org_model:
    config: './config/densenet169.yaml'
    partition_idx: 0

autoencoder:
    type: &ae_type 'input_vae'
    experiment: &ae_experiment !join [*dataset_name, '-', *ae_type]
    ckpt: !join ['./resource/ckpt/autoencoder/', *ae_experiment, '.ckpt']
    params:
        input_channel: 3
        h_dim: 18432
        z_dim: 512

train:
    epoch: 150
    batch_size: 20
    rough_size: 256
    interval: -1
    optimizer:
        type: 'Adam'
        params:
            lr: 0.001
    scheduler:
        type: 'MultiStepLR'
        params:
            milestones: [50, 150]
            gamma: 0.1
    criterion:
        type: 'MSELoss'
        params:
            reduction: 'mean'

test:
    batch_size: 1
