dataset:
    name: &dataset_name 'caltech101'
    root: &data_dir './resource/data/caltech101/'
    data:
        train: !join [*data_dir, 'train.txt']
        valid: !join [*data_dir, 'valid.txt']
        test: !join [*data_dir, 'test.txt']
    normalizer:
        mean:
        std:

input_shape: [3, 224, 224]

org_model:
    type: &org_type 'densenet169'
    config: !join ['./config/', *org_type, '.yaml']
    partition_idx: 3

autoencoder:
    type: &ae_type 'middle_ae'
    experiment: &ae_experiment !join [*dataset_name, '-', *ae_type, '-', *org_type]
    ckpt: !join ['./resource/ckpt/autoencoder/', *ae_experiment, '.ckpt']
    params:
        input_channel: 64
        bottleneck_channel: 3

train:
    epoch: 150
    batch_size: 20
    rough_size: 256
    interval: -1
    optimizer:
        type: 'Adam'
        params:
            lr: 0.001
    scheduler:
        type: 'MultiStepLR'
        params:
            milestones: [50, 150]
            gamma: 0.1
    criterion:
        type: 'MSELoss'
        params:
            reduction: 'mean'

test:
    batch_size: 1
